name: Hello World Workflow

# Trigger the workflow on push events to any branch
on:
  push:
    branches:
      - "**" # This matches all branches including new ones

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello World
        run: echo "hello world"
